### ISSUE TITLE
Source code for Emotion detection with Face API (cloud)

### ISSUE THREAD

**Issue by ArtyomR** [MicrosoftDocs/labs#3]
Hi,

Could you please publish source code for ML lab (https://docs.microsoft.com/en-us/labs/insiderdevtour2018/machinelearning/index?ocid=idt_labs_cta_web2lab_machinelearning&tutorial-step=1)?
I'm not sw developer (code writer). Basicaly I'm product manager. And I have to understand possibility of Microsoft ML stack for my products.
I'm trying to run Machine learning lab (https://docs.microsoft.com/en-us/labs/insiderdevtour2018/machinelearning/index?ocid=idt_labs_cta_web2lab_machinelearning&tutorial-step=2).

I passed all recommended stapes. But the app doesn't work. There are 2 error and 3 warrning messages.
********************* 
Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления
Ошибка	CS0246	Не удалось найти тип или имя пространства имен "FrameEventArgs" (возможно, отсутствует директива using или ссылка на сборку).	AlarmClock	C:\Users\ArtemRadchenko\source\repos\AlarmClock\AlarmClock\MainPage.xaml.cs	63	Активный
Ошибка	CS0123	Нет перегруженного метода для "Preview_FrameArrived", который соответствует делегату "EventHandler<FrameEventArgs>".	AlarmClock	C:\Users\ArtemRadchenko\source\repos\AlarmClock\AlarmClock\MainPage.xaml.cs	58	Активный
Предупреждение	NU1603	runtime.native.System.IO.Compression 4.3.0 зависит от runtime.win10-arm64.runtime.native.System.IO.Compression (>= 4.3.0), но runtime.win10-arm64.runtime.native.System.IO.Compression 4.3.0 не найден. Использовано наилучшее приближенное соответствие runtime.win10-arm64.runtime.native.System.IO.Compression 4.3.1.				
Предупреждение	CS1998	В данном асинхронном методе отсутствуют операторы await, поэтому метод будет выполняться синхронно. Воспользуйтесь оператором await для ожидания неблокирующих вызовов API или оператором await Task.Run(...) для выполнения связанных с ЦП заданий в фоновом потоке.	AlarmClock	C:\Users\ArtemRadchenko\source\repos\AlarmClock\AlarmClock\MainPage.xaml.cs	63	Активный
Предупреждение	CS0168	Переменная "e" объявлена, но ни разу не использована.	AlarmClock	C:\Users\ArtemRadchenko\source\repos\AlarmClock\AlarmClock\MainPage.xaml.cs	112	Активный
**************

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d47c1f9-0c11-727e-1ac9-14d03a67264f
* Version Independent ID: 5a701b6d-48c7-a78d-b081-2384e981c2ac
* Content: [Get started with Machine Learning](https://docs.microsoft.com/en-us/labs/insiderdevtour2018/machinelearning/index?ocid=idt_labs_cta_web2lab_machinelearning&tutorial-step=5)
* Content Source: [labs/insiderdevtour2018/machinelearning/index.yml](https://github.com/MicrosoftDocs/labs-pr/blob/live/labs/insiderdevtour2018/machinelearning/index.yml)
* GitHub Login: @cbarkerms

**Comment by cbarkerms** [comment]
Thank you for raising this issue.  This was due to us moving from preview to release of the Toolkit library and there were a couple of breaking changes.  I have now pushed a fix so please pull the latest code from here: https://github.com/Microsoft/InsiderDevTour18-Labs/

**Comment by cbarkerms** [comment]
closing - please re-open if still having problems
