### ISSUE TITLE
Emotion detection with Windows ML (edge)

### ISSUE THREAD

**Issue by 79212** [MicrosoftDocs/labs#4]
I have a problem with "**1. Detect emotions with a local model and Windows ML:**

1.Download the model from the Azure AI Gallery.

2. In Visual Studio, drag and drop the downloaded FER-Emotion-Recognition.onnx file to the Assets folder in your Solution Explorer. Visual Studio will generate a new FER-Emotion-Recognition.cs file with the necessary code to create and execute the model.

3. Right-click on the FER-Emotion-Recognition.onnx file, select Properties, set Build Action to "Content" and Copy to Output Directory to "Copy if newer"."

Since I am new to Visual Studio, who can recommend me a video which demo the above three steps.

Thanks,
Bintao Li 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d47c1f9-0c11-727e-1ac9-14d03a67264f
* Version Independent ID: 5a701b6d-48c7-a78d-b081-2384e981c2ac
* Content: [Get started with Machine Learning](https://docs.microsoft.com/en-us/labs/insiderdevtour2018/machinelearning/index?ocid=idt_labs_cta_web2lab_machinelearning)
* Content Source: [labs/insiderdevtour2018/machinelearning/index.yml](https://github.com/MicrosoftDocs/labs-pr/blob/live/labs/insiderdevtour2018/machinelearning/index.yml)
* Service: **unspecified**
* Product: **unspecified**
* GitHub Login: @cbarkerms

**Comment by cbarkerms** [comment]
Please see ~5:00 in this video: https://channel9.msdn.com/Shows/ifdefWINDOWS/ifdef-WINML

Closing, but please let me know if you are still having issues.
