### ISSUE TITLE
Loading Onnx file is not work

### ISSUE THREAD

**Issue by Zenylin** [MicrosoftDocs/labs#5]
As the title said, when I run F5 with x64 Local Machine, it show this runtime error, please help, thanks~

this is my environment:
![image](https://user-images.githubusercontent.com/10859662/42667954-c4e0aa82-8680-11e8-949e-5270a275ea00.png)

this is the error message
![image](https://user-images.githubusercontent.com/10859662/42667935-ac20d094-8680-11e8-8433-fa900f3617cb.png)

**Comment by cbarkerms** [comment]
@Zenylin - can you set our min version to 17134 and let me know if the error continues please?

**Comment by cbarkerms** [comment]
please re-open if still having the issue
